#pragma once
#ifdef LILYGO_WATCH_2020_V1
#define LOC_WATCH_MODEL "V1"
#elif LILYGO_WATCH_2020_V2
#define LOC_WATCH_MODEL "V2"
#elif LILYGO_WATCH_2020_V3
#define LOC_WATCH_MODEL "V3"
#endif
#define LOC_LANGUAGE "English"
#define LOC_WIFI "Wifi"
#define LOC_WIFI_SETTINGS "Wifi settings"
#define LOC_WIFI_ENABLE "Enabled"
#define LOC_WIFI_CONNECTED "Connected"
#define LOC_WIFI_CONNECT "Connect"
#define LOC_WIFI_CONFIG_SSID_FMT "Wifi: %s"
#define LOC_WIFI_IP_RSSI_FMT "IP: %s, RSSI: %d dB"
#define LOC_WIFI_CONNECTING "Connecting"
#define LOC_WIFI_CONNECT_SUCCESS "Success! You're now connected to Wifi."
#define LOC_WIFI_DISCONNECTED "Disconnected"
#define LOC_WIFI_OFF "Off"
#define LOC_WIFI_NO_CONFIG "Not configured"
#define LOC_WIFI_PLEASE_CONFIGURE "Please configure Wifi"
#define LOC_WIFI_SCAN_LABEL "Scan"
#define LOC_WIFI_SCANNING_PROGRESS "Scanning Wifi..."
#define LOC_WIFI_SELECT "Select Wifi"
#define LOC_KEYBOARD_DEL "Del"
#define LOC_WIFI_PASSWORD_PROMPT "Enter password"
#define LOC_WIFI_LOST_CONNECTION "Wifi has lost connection to AP!"
#define LOC_WIFI_ASSOC_FAIL "Can't connect to Wifi. Incorrect password, or out of range."
#define LOC_MESSAGEBOX_OK "OK"
#define LOC_MESSAGEBOX_DISABLE_WIFI "Disable Wifi"
#define LOC_SETTINGS_MENU "Watch settings"
#define LOC_SIGNALK_SETTINGS "Signal K settings"
#define LOC_SIGNALK_CONNECTED_FMT "Connected\nDeltas Rx'd: %d"
#define LOC_SIGNALK_DISCONNECTED "Disconnected"
#define LOC_SIGNALK_CONNECTING "Connecting"
#define LOC_SIGNALK_TOKEN_OK "Token OK"
#define LOC_SIGNALK_TOKEN_NONE "No token!"
#define LOC_SIGNALK_TOKEN_PENDING "Pending authorization"
#define LOC_SIGNALK_TOKEN_RESET "Reset token"
#define LOC_SIGNALK_REQUEST_REJECTED "Signal K server rejected authorization!"
#define LOC_SIGNALK_CONNECTION_LOST "Signal K server connection lost! Please reconnect manually!"
#define LOC_SIGNALK_ADDRESS_EMPTY "Set address"
#define LOC_SIGNALK_INPUT_ADDRESS "Enter server address"
#define LOC_SIGNALK_INPUT_PORT "Enter server port (default: 3000)"
#define LOC_SIGNALK_FIND_SERVER "Find SK Server w/ mDNS"
#define LOC_SIGNALK_FINDING_SERVER "Detecting SK server..."
#define LOC_SIGNALK_SYNC_TIME "Sync time with SK Server"
#define LOC_SIGNALK_MDNS_NOT_FOUND "Unable to find SK server!"
#define LOC_SIGNALK_MDNS_ERORR "Unable to initialize mDNS service!"
#define LOC_TIME_SETTINGS "Time settings"
#define LOC_TIME "Time"
#define LOC_DATE "Date"
#define LOC_DATE_FORMAT "%d. %s %d"
#define LOC_INPUT_HOUR "Enter current hour"
#define LOC_INPUT_MINUTE "Enter current minute"
#define LOC_SELECT_DATE "Select current date"
#define LOC_MONTHS {"???","Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"}
#define LOC_WATCH_INFO "Watch info"
#define LOC_WATCH_VERSION "Version 1.0 " LOC_WATCH_MODEL
#define LOC_AUTHOR "Author: Jan Dytrych,\nBrian Smith and contributors"
#define LOC_UPTIME "Uptime: %d:%.2d:%.2d "
#define LOC_WATCH_NAME "Watch\nname:"
#define LOC_INPUT_WATCH_NAME "Watch name (1 - 16 chars)"
#define LOC_WATCH_NAME_EMPTY "Enter watch name"
#define LOC_TIMEZONE "Timezone: "
#define LOC_24HOUR_TIME "Show 24 hour time"
#define LOC_DISPLAY_SETTINGS "Display settings"
#define LOC_SCREEN_TIMEOUT "Screen\ntimeout: "
#define LOC_INPUT_SCREEN_TIMEOUT "Scrn timeout (>=5 sec.)"
#define LOC_WAKEUP_COUNT "Wake-up count: %d"
#define LOC_DISPLAY_BRIGHTNESS "Display\nbrightness: "
#define LOC_DISPLAY_DOWNLOAD_UI "Download DynamicViews"
#define LOC_DISPLAY_DOWNLOADING_UI "Downloading UI from SK server..."
#define LOC_DISPLAY_DOWNLOAD_UI_DONE "The DynamicViews download was successful. Watch will reboot in 5 seconds!"
#define LOC_DISPLAY_DOWNLOAD_UI_NO_CONNECTION "Unable to download DynamicViews!\r\nUnable to connect to SK server!"
#define LOC_DISPLAY_DOWNLOAD_UI_ERROR "Unable to download DynamicViews!\r\nThere was an error in transfer!"
#define LOC_INPUT_DISPLAY_BRIGHTNESS "Disp brightness (1 to 5)"
#define LOC_ON "On"
#define LOC_OFF "Off"
#define LOC_TRUE "True"
#define LOC_FALSE "False"
#define LOC_INPUT_TIMEZONE "Select timezone"
#define LOC_DARK_SWITCH_LABEL "Enable Dark theme"
#define LOC_WAKEUP_SETTINGS_MENU "Wake-up"
#define LOC_WAKEUP_SETTINGS "Wake-up settings"
#define LOC_WAKEUP_TITLE "Select wake-up options"
#define LOC_WAKEUP_DOUBLE_TAP "Double tap"
#define LOC_WAKEUP_TILT "Watch tilt"
#define LOC_WAKEUP_TOUCH "Screen touch"
#define LOC_CLOCK_SETTINGS_MENU "Clock"
#define LOC_DISPLAY_SETTINGS_MENU "Display"
#define LOC_WIFI_SETTINGS_MENU "Wifi"
#define LOC_SIGNALK_SETTING_MENU "Signal K"
#define LOC_WATCH_INFO_MENU "Watch info"
#define LOC_MSG_COUNT " of this msg"
#define LOC_UNREAD_MSGS " unread msgs"
#define LOC_POWER_BATTERY_CHARGED "Battery charging is now complete!"
#define LOC_STARTUP_SPIFFS "SPIFFS init...please wait!"
#define LOC_STARTUP_HW_GUI "Hardware & LVGL init..."
#define LOC_STARTUP_NETWORKING "Wifi & networking init..."
#define LOC_SK_PUT_SEND_FAIL "Unable to send SK put request!"
#define LOC_SK_PUT_SEND_FAIL "Unable to send Signal K put request!"
