#pragma once
#define LOC_LANGUAGE "English"
#define LOC_WIFI "WiFi"
#define LOC_WIFI_SETTINGS "WiFi settings"
#define LOC_WIFI_ENABLE "Enabled"
#define LOC_WIFI_CONNECTED "Connected"
#define LOC_WIFI_CONNECTED_STATUS_FMT "Connected, IP: %s"
#define LOC_WIFI_CONNECTING "Connected"
#define LOC_WIFI_DISCONNECTED "Disconnected"
#define LOC_WIFI_OFF "Off"
#define LOC_WIFI_SCAN_LABEL "Scan"
#define LOC_WIFI_SCANING_PROGRESS "Scanning..."
#define LOC_WIFI_SELECT "Select Wifi"
#define LOC_KEYBOARD_DEL "Del"
#define LOC_WIFI_PASSWORD_PROMPT "Type password"
#define LOC_MESSAGEBOX_OK "OK"
#define LOC_SETTINGS_MENU "Watch settings"
#define LOC_SIGNALK_SETTINGS "Signal K settings"
#define LOC_SIGNALK_CONNECTED "Connected to server %s"
#define LOC_SIGNALK_CONNECTED "Connected to server %s"
#define LOC_SIGNALK_DISCONNECTED "Disconnected"
#define LOC_SIGNALK_CONNECTING "Connecting"
#define LOC_SIGNALK_TOKEN_OK "Token OK"
#define LOC_SIGNALK_TOKEN_NONE "No token!"
#define LOC_SIGNALK_TOKEN_PENDING "Pending authorization"
#define LOC_SIGNALK_REQUEST_REJECTED "Signal K server rejected authorization!"
#define LOC_SIGNALK_SERVER_ADDRESS "Server: %s:%d"
#define LOC_SIGNALK_FIND_SERVER "Find SK Server"
#define LOC_SIGNALK_SYNC_TIME "Sync time with SK Server"
#define LOC_TIME_SETTINGS "Watch time"
#define LOC_TIME "Time"
#define LOC_DATE "Date"
#define LOC_DATE_FORMAT "%d. %s %d"
#define LOC_INPUT_HOUR "Type current hour"
#define LOC_INPUT_MINUTE "Type current minute"
#define LOC_SELECT_DATE "Select current date"
#define LOC_MONTHS {"???","Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"}
#define LOC_WATCH_INFO "Watch info"
#define LOC_WATCH_VERSION "Version 0.0.1"
#define LOC_AUTHOR "Author: Jan Dytrych"
#define LOC_UPTIME "Uptime: %d:%.2d:%.2d "
#define LOC_24HOUR_TIME "Show 24 hour time"